// Pure helpers for clipping element rects to the slide canvas. Decks
// commonly wrap their canvas in `overflow: hidden` and then place
// decorative primitives (radial-gradient orbs, full-bleed images) past
// the canvas edges with the assumption that the wrapper will clip them.
// PowerPoint has no equivalent ancestor-clip mechanism — shapes are
// emitted at their full rect — so any primimg fallback whose source
// element extends past the canvas would otherwise spill into the
// presenter view. The extract-pw primitive-screenshot loop runs every
// candidate rect through `intersectSlide` before invoking
// `page.screenshot({clip})`, and replaces the primitive's recorded rect
// with the intersection so measureToIR / pptx-build emit at the
// correctly clipped position.

export const CANVAS_W = 1920;
export const CANVAS_H = 1080;

export type Rect = { x: number; y: number; w: number; h: number };

export function intersectSlide(
  rect: Rect,
  canvasW: number = CANVAS_W,
  canvasH: number = CANVAS_H,
): Rect {
  const x1 = Math.min(canvasW, Math.max(0, rect.x));
  const y1 = Math.min(canvasH, Math.max(0, rect.y));
  const x2 = Math.min(canvasW, Math.max(0, rect.x + rect.w));
  const y2 = Math.min(canvasH, Math.max(0, rect.y + rect.h));
  const w = Math.max(0, x2 - x1);
  const h = Math.max(0, y2 - y1);
  return { x: x1, y: y1, w, h };
}

// Returns true when the rect extends past the slide canvas by more
// than `tolerancePx` on any side. Used by extract-pw to promote a
// native text/decor/svg leaf to ImageFallback so the leaf-screenshot
// path can crop the visible portion. Without this promotion, the
// native shape would emit at its original rect — half off-slide,
// because PowerPoint has no ancestor-clip mechanism to honour the
// HTML overflow:hidden on the slide canvas.
export function overflowsCanvas(
  rect: Rect,
  tolerancePx: number = 5,
  canvasW: number = CANVAS_W,
  canvasH: number = CANVAS_H,
): boolean {
  return (
    rect.x < -tolerancePx ||
    rect.y < -tolerancePx ||
    rect.x + rect.w > canvasW + tolerancePx ||
    rect.y + rect.h > canvasH + tolerancePx
  );
}

// A 1×1 fully-transparent PNG. Used as a placeholder fallback image
// when a primitive's source rect intersects the slide canvas as a
// zero-area region — the primitive is wholly off-canvas, so there is
// nothing to screenshot, but measureToIR still needs `fallbackImageDataUrl`
// to be set so the primitive enters the cascade-suppression set
// (otherwise its descendant text/decor leaves would emit natively at
// their own off-canvas positions).
// Generated by pngjs's PNG.sync.write of a fresh new PNG({width:1, height:1}).
// pngjs is strict about trailing bytes during decode — the post-release-check
// Gate 2 helper roundtrips the embedded PNG through PNG.sync.read for diffing,
// so this constant must be a byte sequence that pngjs itself accepts back.
export const TRANSPARENT_PNG_1X1 =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4AWMAAQAABQABNtCI3QAAAABJRU5ErkJggg==';
